# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDwR0n50H9iIhcOm186NtgH2oq_Dalsg
"""

score=input().split()
count=0
for i in score:
  if int(i)<60:
    count+=1
print("不及格的人數：",count)